#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.username=root
#spring.data.mongodb.password=password
#spring.data.mongodb.database=products
spring.data.mongodb.uri=mongodb://root:password@localhost:27017/mystore?authSource=admin

spring.data.mongodb.auto-index-creation=true
#spring.data.mongodb.authentication-database=admin

my.component.value=Hello, World!